version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mendomarket
      POSTGRES_PASSWORD: mendomarket
      POSTGRES_DB: mendomarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mendomarket"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://mendomarket:mendomarket@db:5432/mendomarket

volumes:
  postgres_data: